version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bitvec
    versions:
    - 0.21.0
    - 0.22.0
    - 0.22.1
