[package]
name = "uuid"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"

[dependencies]
md-5 = "0.9.0"
sha-1 = "0.9.1"

[dependencies.bitvec]
version = "0.17.4"
default-features = false
features = []

[dependencies.rand]
version = "0.7.3"
default-features = false
features = []

[features]
default = []

# Enable usage of `getrandom`.
# This can be used in no_std environments, but usually requires OS system libraries.
getrandom = [
    "rand/getrandom"
]
