[package]
name = "uuid"
version = "0.1.0"
authors = ["Diana"]
edition = "2018"

[dependencies.bitvec]
version = "0.17.4"
default-features = false
features = []

[dependencies.rand]
version = "0.7.3"
# default-features = false
features = []
